-keep class com.google.android.gms.ads.** { *; }
-keep interface com.google.android.gms.ads.** { *; }
-keep class com.google.android.gms.common.** { *; }
-keep class io.flutter.plugins.googlemobileads.** { *; }
-keep class io.flutter.embedding.engine.plugins.** { *; }
-keep class com.google.android.gms.ads.internal.ClientApi { *; }
